### ISSUE TITLE
11月26日失效

### ISSUE THREAD

**Issue by heng0314** [straightedge4life/jetbrains-agent#2]

**Comment by tobeforever** [comment]
+1

**Comment by Devil-Cong** [comment]
+1

**Comment by hkbaicfl** [comment]
试一下下面这个：
`

KC4CPs/mH19e7ze1GXfrQH1uVsZ+i1bDpeffO9FzA7pligqeLiXrrrm+IQugrHMlTOo3VZRzlhXOWCtetc6N0Q2n3BONIBwZP/1AJqid6e3pcqbVl7PLzMpWfTsWPcE8JkXhlopYgIADMSTwkm2MwMkPCkBiHAXAfJxwzoOgmIE
--


`

**Comment by straightedge4life** [comment]
> 
> 
> 试一下下面这个：
> 
> KC4CPs/mH19e7ze1GXfrQH1uVsZ+i1bDpeffO9FzA7pligqeLiXrrrm+IQugrHMlTOo3VZRzlhXOWCtetc6N0Q2n3BONIBwZP/1AJqid6e3pcqbVl7PLzMpWfTsWPcE8JkXhlopYgIADMSTwkm2MwMkPCkBiHAXAfJxwzoOgmIE

试了下这个安装参数，可以用，非常感谢。
